(ItemName as text)=>
let
    Источник = Excel.Workbook(File.Contents(File), null, true),
    #"ItemName" = Источник{[Item=ItemName,Kind="Sheet"]}[Data],
    #"Повышенные заголовки" = Table.PromoteHeaders(#"ItemName", [PromoteAllScalars=true]),
    Пользовательская2 = Table.ColumnNames(#"Повышенные заголовки"),
    #"Преобразовано в таблицу" = Table.FromList(Пользовательская2, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Добавлен индекс1" = Table.AddIndexColumn(#"Преобразовано в таблицу", "Индекс", 0, 1),
    #"Добавлен пользовательский объект" = Table.AddColumn(#"Добавлен индекс1", "Пользовательская", each Table.FindText(#"Добавлен индекс1", "НАЧАЛО")[Индекс]{0})[Пользовательская]{0}
in
    #"Добавлен пользовательский объект"
	
	
	
let
    Источник = Excel.Workbook(File.Contents(File), null, true),
    #"Строки с примененным фильтром" = Table.SelectRows(Источник, each Text.Contains([Kind], "Sheet")),
    #"Другие удаленные столбцы1" = Table.SelectColumns(#"Строки с примененным фильтром",{"Item", "Data"}),
    #"Добавлен индекс" = Table.AddIndexColumn(#"Другие удаленные столбцы1", "Индекс", 0, 1, Int64.Type),
    #"Добавлен пользовательский объект" = Table.AddColumn(#"Добавлен индекс", "Индекс столбца", each ф_индекс_столбца([Item])),
    #"Добавлен пользовательский объект2" = Table.AddColumn(#"Добавлен пользовательский объект", "Пользовательский.1", each Table.SelectColumns(#"Добавлен пользовательский объект"[Data]{[Индекс]}, List.Range(Table.ColumnNames(#"Добавлен пользовательский объект"[Data]{[Индекс]}), [Индекс столбца], 7))),
    #"Другие удаленные столбцы" = Table.SelectColumns(#"Добавлен пользовательский объект2",{"Item", "Пользовательский.1"}),
    #"Добавлен пользовательский объект1" = Table.AddColumn(#"Другие удаленные столбцы", "Пользовательский", each Table.PromoteHeaders(Table.Skip([Пользовательский.1], 3))),
    #"Добавлен пользовательский объект3" = Table.AddColumn(#"Добавлен пользовательский объект1", "Пользовательский.2", each Table.AddIndexColumn([Пользовательский], "Index", 0)),
    #"Добавлен пользовательский объект4" = Table.AddColumn(#"Добавлен пользовательский объект3", "End", each Table.FindText([Пользовательский.2], "КОНЕЦ")[Index]{0}),
    #"Добавлен пользовательский объект5" = Table.AddColumn(#"Добавлен пользовательский объект4", "Пользовательский.3", each Table.FirstN([Пользовательский.2], [End])),
    #"Другие удаленные столбцы2" = Table.SelectColumns(#"Добавлен пользовательский объект5",{"Пользовательский.3"}),
    #"Развернутый элемент Пользовательский.3" = Table.ExpandTableColumn(#"Другие удаленные столбцы2", "Пользовательский.3", {"Column1", "НУЖНО", "НУЖНО_1", "НУЖНО_2", "НУЖНО_3", "НУЖНО_4", "НУЖНО_5"}, {"Column1", "НУЖНО", "НУЖНО_1", "НУЖНО_2", "НУЖНО_3", "НУЖНО_4", "НУЖНО_5"})
in
    #"Развернутый элемент Пользовательский.3"